#!/usr/bin/env bash
echo "Installing the server on this machine on local (localhost)..."
if [ -z "$SUDO_USER" ]; then
    echo "Run this script with sudo, you dumbass"
    exit 1
fi

chmod +x ./pre-install.sh
./pre-install.sh

rm -v /usr/local/bin/fxhub

mkdir -pv /opt/fxhub
cp -v ./fxhub /opt/fxhub/fxhub
cp -v ./version /opt/fxhub/version
cp -v ./dependencies /opt/fxhub/dependencies

chmod +x /opt/fxhub/fxhub

echo "all files needed copied."

echo "creating user systemd dir..."

ACTUAL_USER="$SUDO_USER"
USER_ID=$(id -u "$ACTUAL_USER")

mkdir -p "/home/$ACTUAL_USER/.config/systemd/user"

rm "/home/$ACTUAL_USER/.config/systemd/user/fxhub.service"
echo "service removed"
cp ./fxhub.service "/home/$ACTUAL_USER/.config/systemd/user/fxhub.service"
echo "service file copied"
chmod 777 -R /opt/fxhub

echo "fxhub installed. Configuring the server (systemctl) now."
chmod +x ./post-install.sh
./post-install.sh
